apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: subnet-team-a
  namespace: team-a
  labels:
    demo.crossplane.io/stack: team-a
    demo.crossplane.io/role: subnet
spec:
  forProvider:
    addressPrefixes:
      - 10.0.1.0/24
    privateEndpointNetworkPolicies: Disabled
    resourceGroupNameSelector:
      matchLabels:
        demo.crossplane.io/stack: team-a
        demo.crossplane.io/role: resource-group
    virtualNetworkNameSelector:
      matchLabels:
        demo.crossplane.io/stack: team-a
        demo.crossplane.io/role: virtual-network
